### ISSUE TITLE
Cannot download RH024.ova from guide

### ISSUE THREAD

**Issue by michele-mogul** [extraordy/rh024#1]
Following this file: "extraordy/rh024/tree/master/guides/vbox-install" chapter 3, the link that refers to the RH024.ova image is a self reference link that doesn't let us download the image. 

Maybe there is something i am missing? 
Let me know, thanks in advice.

**Comment by venric75** [comment]
I've the same problem

**Comment by extraordy** [comment]
Broken link fixed.
