### ISSUE TITLE
Mancata ricezione email di verifica

### ISSUE THREAD

**Issue by gponteduro** [extraordy/rh024#10]
Salve,
ho effettuato la registrazione sul portale Redhat ma non ricevo nessuna email di Verifica.
L'username è g.ponteduro e l'indirizzo email è: g.ponteduro@reply.it.

Potete aiutarmi a risolvere.

Grazie mille,
Giuseppe

**Comment by ValentinoUberti** [comment]
Per la mancata ricezione alla registrazione RedHat devi contattare il supporto RedHat
