### ISSUE TITLE
Oracle Solaris Zones e Linux Containers

### ISSUE THREAD

**Issue by francescocb** [extraordy/rh024#101]
dal vostro punto di vista quante similitudini ci sono?

**Comment by luca-af** [comment]
Entrambi sono molto simili (isolare applicazioni) ma i linux container nascono da delle primitive del kernel (CGroups e namespaces) e sono molto flessibili rispetto alle Solaris Zones.

Ti lascio [qui](https://blog.jessfraz.com/post/containers-zones-jails-vms/) un blogpost di Jessie Franzelle in merito ad un confronto tra Zones, Jail e Container.
