### ISSUE TITLE
VDO

### ISSUE THREAD

**Issue by fracarfzx** [extraordy/rh024#102]
potreste ricondividere dove si trova il documento su VDO?

Grazie

**Comment by edocod1** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/deduplicating_and_compressing_storage/deploying-vdo_deduplicating-and-compressing-storage

**Comment by fracarfzx** [comment]
ottimo, grazie!

E' possibile anche avere il link al post su VDO a cui si faceva riferimento
durante la sessione?

Grazie!!!

------------------------------------------------------
*Francesco Carlini*
[image: CMIT.IT] <http://www.cmit.it>
<http://www.cmit.it>
Via Bassano del Grappa 4
00195 Roma

E-Mail: francesco.carlini@cmit.it
Mobile: +39 3892475954
-------------------------------------------------------

**************************************

I suoi dati saranno trattati lecitamente, nel rispetto della normativa
sulla protezione dei dati personali (Reg. 679/2016/UE), per le finalità
determinate da CMIT S.r.l. come Titolare del trattamento, con modalità
analogiche ed elettroniche. Senza i suoi dati, alcuni necessari per legge,
non potremo espletare l'operazione richiesta. I suoi dati potranno essere
comunicati a terzi, nei casi ammessi, ma non verranno diffusi. Può
esercitare i diritti previsti dagli artt. 15 ss Reg. 679/2016/UE inviando
una richiesta ai recapiti indicati nell'intestazione o all'e-mail
privacy@cmit.it. Informativa completa sul sito www.cmit.it."
**************************************


Il giorno gio 9 apr 2020 alle ore 18:27 Edoardo Codeglia <
notifications@github.com> ha scritto:

**Comment by edocod1** [comment]
https://www.extraordy.com/vdo-virtual-data-optimizer-per-la-migliore-gestione-dello-spazio-disco-con-la-de-duplica-su-rhel8-e-centos8/

Tutto tuo! :smile:

**Comment by fracarfzx** [comment]
Perfetto, grazie!!!

------------------------------------------------------
*Francesco Carlini*
[image: CMIT.IT] <http://www.cmit.it>
<http://www.cmit.it>
Via Bassano del Grappa 4
00195 Roma

E-Mail: francesco.carlini@cmit.it
Mobile: +39 3892475954
-------------------------------------------------------

**************************************

I suoi dati saranno trattati lecitamente, nel rispetto della normativa
sulla protezione dei dati personali (Reg. 679/2016/UE), per le finalità
determinate da CMIT S.r.l. come Titolare del trattamento, con modalità
analogiche ed elettroniche. Senza i suoi dati, alcuni necessari per legge,
non potremo espletare l'operazione richiesta. I suoi dati potranno essere
comunicati a terzi, nei casi ammessi, ma non verranno diffusi. Può
esercitare i diritti previsti dagli artt. 15 ss Reg. 679/2016/UE inviando
una richiesta ai recapiti indicati nell'intestazione o all'e-mail
privacy@cmit.it. Informativa completa sul sito www.cmit.it."
**************************************


Il giorno gio 9 apr 2020 alle ore 18:32 Edoardo Codeglia <
notifications@github.com> ha scritto:
