### ISSUE TITLE
Virtual Box 

### ISSUE THREAD

**Issue by Dome80** [extraordy/rh024#108]
Ciao, ho importato la macchina in VirtualBox, volevo sapere come fare per modificare la risoluzione video. Grazie

**Comment by Dome80** [comment]
> Ciao, ho importato la macchina in VirtualBox, volevo sapere come fare per modificare la risoluzione video. Grazie

**Comment by Procsiab** [comment]
Buongiorno, se sta usando la macchina virtuale proposta nella nostra guida, essa è priva di ambiente grafico desktop, dunque non è possibile modificare la risoluzione e l'unica interazione col sistema guest è tramite tastiera; se desidera provare RHEL con ambiente grafico, può scaricarlo dal portale dedicato ai [**developer**](https://developers.redhat.com/products/rhel/download) Red Hat (deve prima effettuare la sottoscrizione, come mostrato nella [**guida**](https://github.com/extraordy/rh024/tree/master/guides/rhdev-subscribe#1-iscrizione-a-red-hat-developer))
