### ISSUE TITLE
Informazioni e chiarimenti

### ISSUE THREAD

**Issue by Sab1025** [extraordy/rh024#109]
Buongiorno

ho seguito il corso di ieri pomeriggio. Ho provato a porre la domanda sulla chat di youtube ma data la mole di persone non ho ricevuto risposta.
Io non ho nessuna conoscenza  base di linux, sorvolando sulla durata del corso senza pause (dopo la seconda ora non riuscivo più a capire molto) volevo capire se suddetto corso era per persone con basi o meno. Anche laddove speravo di trovare qualche appiglio, mi riferisco ai labs, sono giusto qualche spunto preso da quello che è stato detto nel corso.
Sostanzialmente non sento di aver appreso granché, sono io che non sono stato attento o non era il corso adatto a me?

Grazie

**Comment by extraordy** [comment]
Buongiorno contatti pure training@extraordy.com, il nostro staff le risponderà nel dettaglio
