### ISSUE TITLE
avvio della macchina virtuale

### ISSUE THREAD

**Issue by Ang238** [extraordy/rh024#110]
Buon giorno, 
perdonate la domanda abbastanza ignorante. Ho scaricato la virtualbox per Win10, ho scaricato e provato ad avviare la macchina seguendo le vostre indicazioni, ma non parte e mi dà quest'errore: 

Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).
Codice di uscita: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaccia: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Posso chiedervi cosa dovrei fare per risolvere questo problema? Grazie.

**Comment by fabrizio-sudo** [comment]
Ciao, per far girare virtualbox il processore sul tuo pc deve avere
a) un processore che supporta appunto la virtualizzazione
b) nel Bios questo supporto deve essere abilitato

il tuo errore dice "VT-x is disabled in the BIOS". Per non dare mai nulla per scontato, hai mai aperto / visto un BIOS?

**Comment by Ang238** [comment]
Ciao Fabrizio, grazie per la risposta. Premetto che ho una conoscenza molto scarsa in materia, per cui potrebbero essermi sfuggite delle ovvietà. Ho aperto raramente il BIOS, in genere per problemi di funzionamento e con delle specifiche indicazioni. Credo sia comunque un problema di abilitazione, perché ho scaricato Securable e il processore sembra supportare la virtualizzazione. Come posso procedere? Devo riavviare ed eseguire manualmente dal BIOS?

**Comment by fabrizio-sudo** [comment]
Esattamente. all'avvio premi il tasto deputato (in genere canc o F2) per entrare nel bios per poi cercare l'opzione giusta nella sezione dedicata alla cpu. in genere le opzioni sono ENABLE, DISABLE e forse AUTO, insomma difficile sbagliare. [ qui](https://www.youtube.com/watch?v=EPDzCvrUl0U) un video di esempio molto breve, la ricerca che ho eseguito è 'come abilitare nel BIOS VT-x'. Non ti dò personalmente indicazioni perché dovrei vedere le schermate. Fammi sapere!
