### ISSUE TITLE
Virtual Box - Mac - OS X - Catalina

### ISSUE THREAD

**Issue by AntonioDEM** [extraordy/rh024#113]
Salve
Vorrei sapere cortesemente come posso installare la virtual machine su Osx, 
installando Virtual Box o Parallel potrei caricare il file .ova?

Grazie

**Comment by michelevecchiato** [comment]
@AntonioDEM Scusa la risposta banale, immagino tu abbia già seguito le istruzioni [[1](https://www.virtualbox.org/manual/UserManual.html#installation-mac)] del "User Manual" di Oracle VirtualBox per Mac OS X. La procedura di "import" del file *.ova è uguale per tutti. Segui dal passo 3 ("_Importare la macchina virtuale_") la guida[[2](https://github.com/extraordy/rh024/blob/master/guides/vbox-install/README.md)]

**Comment by AntonioDEM** [comment]
@michelevecchiato  Salve
si ho risolto tutto grazie.
