### ISSUE TITLE
Attestato di partecipazione

### ISSUE THREAD

**Issue by dbertino** [extraordy/rh024#114]
Buongiorno, ho compilato il form per l'attestato, sono ancora da inviare o c'è stato qualche problema con la richiesta?
Grazie mille

**Comment by brno86** [comment]
Salve, anche a me non è ancora arrivato l'attestato. C'è solo qualche piccolo ritardo o conviene che rifaccio la richiesta?
Grazie mille.

**Comment by maagnolu** [comment]
Buonasera,
anche a me l'attestato non è ancora arrivato. Ci sono dei problemi oppure bisogna solo aspettare?
Grazie mille

**Comment by Procsiab** [comment]
Buonasera, per problemi con la ricezione degli attestati scrivete all'indirizzo training@extraordy.com, usando la mail con la quale vi siete iscritti.
