### ISSUE TITLE
Subscription - network error

### ISSUE THREAD

**Issue by rcomas28** [extraordy/rh024#115]
Ben trovati,
seguendo la procedura per attivare la sottoscrizione do, sostituendo user e password, il comando:
subscription-manager register --username RHID --password PASSWORD
Ottengo questo messaggio di errore:
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information
Uso VirtualBox 6.1 su MacOS 10.15.3
Mi potete aiutare? Grazie

Marco

**Comment by Procsiab** [comment]
Buonasera, provi ad eseguire questo comando invece:
```bash
subscription-manager register
```
Le verranno richiesti ID Red Hat inserito in fase di iscrizione (non la mail) e la password, su due riche distinte (l'inserimento della password avverrà senza mostrare i caratteri digitati). In questo modo se ha dei caratteri speciali nella password che vengono interpretati dalla shell diversamente da una stringa, il problema dovrebbe risolversi. In caso contrario, il problema potrebbe essere legato alla sua configurazione di rete, e a questo proposito la rimando alla [**documentazione**](https://www.virtualbox.org/manual/UserManual.html) di VIrtualBox
