### ISSUE TITLE
RH non si avvia su Virtual Box MacOSX 10.15.4

### ISSUE THREAD

**Issue by silvanop74** [extraordy/rh024#12]
Salve, ho installato Virtual Box su Mac con OSX 10.15.4 e scaricato l’immagine RH ma la macchina virtuale non parte (Error: Kernel driver not installed rc=-1908).

**Comment by ValentinoUberti** [comment]
Salve, ecco la fix:
https://www.howtogeek.com/658047/how-to-fix-virtualboxs-%E2%80%9Ckernel-driver-not-installed-rc-1908-error/

**Comment by silvanop74** [comment]
OK funziona, grazie

**Comment by ValentinoUberti** [comment]
Perfetto a domani
