### ISSUE TITLE
KVM e RH024 su distro Parrot

### ISSUE THREAD

**Issue by andreasgreccia** [extraordy/rh024#13]
Buongiorno io ho appena installato la vostra immagine RH024 e seguito il tutorial allegato, sul mio pc windows (tutto è andato a buon fine).

Ora ho anche un vecchio portatile con installata la distro  “Parrot”,  posso provare ad installare su questo la  RH024 seguendo il vostro tutorial, oppure potrei incappare in qualche problema di tecnico e/o di licenza?

Grazie mille

Andrea

**Comment by ValentinoUberti** [comment]
Buongiorno Andrea, l'immagine della vm non è stata testata con Parrot

**Comment by andreasgreccia** [comment]
Ok magari provo e se non và  pazienza :-).
Un dubbio che ho è relativo all'istruzione sotto

subscription-manager register --username RHID --password PASSWORD

Con la stessa username posso registrare anche la eventuale immagine sull'altro pc , o vengo bloccato?
grazie

**Comment by ValentinoUberti** [comment]
subscription-manager registra una macchina. Di norma con la subscription developer si possono registrare più macchine

**Comment by andreasgreccia** [comment]
ok
