### ISSUE TITLE
Fedora al posto di RH8

### ISSUE THREAD

**Issue by Nik-ve** [extraordy/rh024#14]
Salve a tutti

Mi sono iscritto per il corso di domani. Io ho installato l'ultima versione di Fedora su un pc, mentre seguirò la lezione dal mio Mac. Può andare bene lo stesso o devo virtualizzare una redhat 8 sul mac?

grazie mille
Nicola

**Comment by ValentinoUberti** [comment]
Salve l'ottimale sarebbe avere un RedHat8 virtualizzata su Mac, in alternativa una Fedora 31 o Centos 8 vanno bene
