### ISSUE TITLE
Problema con comando subscription-manager register

### ISSUE THREAD

**Issue by matdev20** [extraordy/rh024#16]
Nella procedura di registrazione dopo l'esecuzione del comando
`subscription-manager register --username RHID --password PASSWORD`
ho riscontrato questo errore:
`HTTP error (401 - Unauthorized): Service not available, please try again later.`
Leggendo velocemente sui forum ho trovato una piccola soluzione che potrebbe essere utile a chi potrebbe avere lo stesso problema https://access.redhat.com/solutions/4173071 
In pratica eseguendo i seguenti comandi è possibile aggirare la problematica:
 `subscription-manager clean`
`subscription-manager register --username=<login_Id>`
`subscription-manager attach --auto`

**Comment by ValentinoUberti** [comment]
Esatto, grazie della condivisione
