### ISSUE TITLE
Non carica la macchina virtuale RH024

### ISSUE THREAD

**Issue by Elena400** [extraordy/rh024#17]
Salve, dopo aver importato la macchina virtuale su virtualbox, l' avvio, visualizza il grub e dopo il grub rimane lo schermo nero e non appare mai il login. Premetto che uso come SO linux FerenOS.

Saluti

**Comment by ValentinoUberti** [comment]
Salve la vm non è stata testata per FerenOS. Potrebbe comunque allegare i log di VirtualBox?

**Comment by Nik-ve** [comment]
Salve
io ho lo stesso problema. Ecco cosa risponde il sistema.

[nicolabergamo@new-host-2 RH024]$ sudo virsh define --file rh024.xml
errore: Impossibile definire il dominio da rh024.xml
errore: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 

Utilizzo una Fedora 31 aggiornata ad oggi. Premetto che il PC che utilizzo è abbastanza obsoleto, ma per quello che devo fare con Fedora è più che sufficiente. 
Grazie

**Comment by luca-af** [comment]
Ciao @Nik-ve quella è una issue diversa rispetto a quella originale, la puoi tracciare con un'altra issue?
