### ISSUE TITLE
Download RH024.ova google drive

### ISSUE THREAD

**Issue by TullioC** [extraordy/rh024#19]
Spiacenti. Al momento non puoi né visualizzare né scaricare il file.

Questo file è stato visualizzato o scaricato da troppi utenti di recente. Prova ad accedere di nuovo in un secondo momento. Se il file a cui stai tentando di accedere è particolarmente grande o è condiviso con molte persone, potresti dover attendere fino a 24 ore prima di poterlo visualizzare o scaricare. Se trascorse le 24 ore non riesci ancora ad accedere al file, rivolgiti all'amministratore del tuo dominio.

**Comment by kubealex** [comment]
Buonasera, siamo al lavoro per risolvere il problema. Grazie per la segnalazione!

**Comment by luca-af** [comment]
Ciao,
il link è stato fixato.

Prova a riaprire nuovamente il documento della guida.

**Comment by TullioC** [comment]
Grazie !
