### ISSUE TITLE
Kvm start

### ISSUE THREAD

**Issue by giannibassiniprovincia** [extraordy/rh024#2]
Salve
**sudo virsh start RH024** 
segnala: 

Errore nell'avvio del dominio: internal error: process exited while connecting to monitor: 2020-04-08T09:58:39.910597Z qemu-system-x86_64: -machine pc-q35-4.1,accel=kvm,usb=off,vmport=off,dump-guest-core=off: unsupported machine type
Use -machine help to list supported machines

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1420, in startup
    self._backend.create()
  File "/usr/lib64/python3.7/site-packages/libvirt.py", line 1080, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2020-04-08T09:58:39.910597Z qemu-system-x86_64: -machine pc-q35-4.1,accel=kvm,usb=off,vmport=off,dump-guest-core=off: unsupported machine type
Use -machine help to list supported machines

**Comment by luca-af** [comment]
Ciao,
riesci a postare l'output di `qemu-system-x86_64 -machine help` e di `which qemu-system-x86_64`?

**Comment by giannibassiniprovincia** [comment]
[gia_bass@sys-ced-05 ~]$ sudo qemu-system-x86_64 -machine help
Supported machines are:
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-3.0)
pc-i440fx-3.0        Standard PC (i440FX + PIIX, 1996) (default)
pc-i440fx-2.9        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.8        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.7        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.6        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.5        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.4        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.3        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.2        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.12       Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.11       Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.10       Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.1        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.0        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.7        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.6        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.5        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.4        Standard PC (i440FX + PIIX, 1996)
pc-1.3               Standard PC (i440FX + PIIX, 1996)
pc-1.2               Standard PC (i440FX + PIIX, 1996)
pc-1.1               Standard PC (i440FX + PIIX, 1996)
pc-1.0               Standard PC (i440FX + PIIX, 1996)
pc-0.15              Standard PC (i440FX + PIIX, 1996)
pc-0.14              Standard PC (i440FX + PIIX, 1996)
pc-0.13              Standard PC (i440FX + PIIX, 1996)
pc-0.12              Standard PC (i440FX + PIIX, 1996)
pc-0.11              Standard PC (i440FX + PIIX, 1996) (deprecated)
pc-0.10              Standard PC (i440FX + PIIX, 1996) (deprecated)
q35                  Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-3.0)
pc-q35-3.0           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.9           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.8           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.7           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.6           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.5           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.4           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.12          Standard PC (Q35 + ICH9, 2009)
pc-q35-2.11          Standard PC (Q35 + ICH9, 2009)
pc-q35-2.10          Standard PC (Q35 + ICH9, 2009)
isapc                ISA-only PC
none                 empty machine
xenfv                Xen Fully-virtualized PC
xenpv                Xen Para-virtualized PC
[gia_bass@sys-ced-05 ~]$

[gia_bass@sys-ced-05 ~]$ which qemu-system-x86_64
/usr/bin/qemu-system-x86_64

Fedora 29

**Comment by luca-af** [comment]
Non avevamo testato con Fedora 29, il problema è ovviamente il machine type impostato.

Puoi usare:

- virt-manager per modificare l'xml della macchina importata
- usare il comando `sudo virsh edit RH024`

In entrambi i casi devi modificare la linea contenente `machine="pc-q35-4.1" ` con `machine="pc-q35" `

**Comment by giannibassiniprovincia** [comment]
ho sostituito machine="pc-q35-4.1" con machine="q35"  e ha funzionato 
Grazie
