### ISSUE TITLE
Impossibile definire il dominio da rh024.xml

### ISSUE THREAD

**Issue by Nik-ve** [extraordy/rh024#20]
Salve
io ho lo stesso problema. Ecco cosa risponde il sistema.

[nicolabergamo@new-host-2 RH024]$ sudo virsh define --file rh024.xml
errore: Impossibile definire il dominio da rh024.xml
errore: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 

Utilizzo una Fedora 31 aggiornata ad oggi. Premetto che il PC che utilizzo è abbastanza obsoleto, ma per quello che devo fare con Fedora è più che sufficiente. 
Grazie

_Originally posted by @Nik-ve in https://github.com/extraordy/rh024/issues/17#issuecomment-611177540_

**Comment by Kakihara73** [comment]
Giorno,
Avevo stesso problema con suse. Mi mancava da installare tutta la parte virt come aggiornato poi nella pagina ufficiale del corso

**Comment by Nik-ve** [comment]
Salve
ho usato Gnome box e per ora pare funzionare. Grazie mille ma avevo provveduto a seguire tutte le indicazioni, alla fine ho trovato il problema, era nel Bios del mio HP
