### ISSUE TITLE
The native API dll was not found (C:\WINDOWS\system32\WinHvPlatform.dll

### ISSUE THREAD

**Issue by ramazzarello** [extraordy/rh024#22]
Salve. Ho provato a caricare la macchina virtuale scaricata, e vedo l'errore copiato nell'oggetto.
è un Windows 10 Pro.
Ho visto le altre proposte di risoluzione e non hanno funzionato.
Potreste gentilmente informarmi se avete un altro workaround da provare per risolvere questo problema?
Grazie
Codice di uscita: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaccia: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by Kakihara73** [comment]
ho trovato in rete qualcosa di simile. dicono di abilitare hyperv nelle funzionalità di windows. cosi:

Finally, here are the things that I have noted down, besides the ones in the FAQ. Look in the "Control Panel" » "Programs and Features" » "Turn Windows features on or off", and make sure that the none of the following are active:

    Hyper-V
    Virtual Machine Platform
    Windows Hypervisor Platform

And finally if you have anything that resembles hardware acceleration, disable it. Some antivirus programs do that.

sorgente: https://forums.virtualbox.org/viewtopic.php?t=92111

**Comment by kubealex** [comment]
Per completezza, è indicato di disabilitare le suddette funzionalità.

**Comment by ramazzarello** [comment]
è disabilitata la configurazione  ma, comunque, non funziona lo stesso.

![immagine](https://user-images.githubusercontent.com/63350422/78892917-884b9c00-7a6a-11ea-8b70-48dd97a0587d.png)

**Comment by maxvicari** [comment]
Rilancia l'eseguibile di virtualbox, seleziona la voce "ripara" e una volta finita l'operazione riavvia il pc. 
Avevo il tuo stesso errore e per me ha funzionato
