### ISSUE TITLE
E' possibile caricare ova rh024 su VMware fusion?

### ISSUE THREAD

**Issue by marchio83** [extraordy/rh024#25]
Nel farlo mi restituisce: 
Line 99: Unsupported element 'StorageItem'.
Line 108: Unsupported element 'StorageItem'.
Line 117: Unsupported element 'StorageItem'.

**Comment by Procsiab** [comment]
Buongiorno, il file OVA che proponiamo è destinato ad essere usato su VirtualBox (testato con la versione 6.1.4)

**Comment by Procsiab** [comment]
Potrei indirizzarla su questo articolo, dove viene suggerito di convertire il file OVA usando l'OVF Tool di VMWare:
https://communities.vmware.com/thread/615830

**Comment by gianlucaceci** [comment]
se converti la ova ti funziona sia sul fusion che sul workstation

**Comment by luca-martino** [comment]
gira anche su VMWare Workstation Pro 15.5 (nel mio caso su Fedora) ma occorre che sia "esportata" da Virtualbox nel formato 1.0

**Comment by jackrm85** [comment]
io ho convertito i file di virtualbox in vmdk con qemu
