### ISSUE TITLE
Errore creazione KVM

### ISSUE THREAD

**Issue by ale-dep** [extraordy/rh024#26]
Su un sistema RHEL 8.1, provando a lanciarla sia con il comando curl, che manualmente, ottengo il seguente errore

[   0,0] Opening the source -i libvirtxml /tmp/rh024.xml
[   0,0] Creating an overlay to protect the source from being modified
[   0,0] Initializing the target -o libvirt -os default

virt-v2v: error: internal error: invalid argument: cannot find libvirt pool 
‘default’: Storage pool not found: no storage pool with matching name 
'default'

Use ‘virsh pool-list --all’ to list all available pools, and ‘virsh 
pool-dumpxml <pool>’ to display details about a particular pool.

To set the pool which virt-v2v uses, add the ‘-os <pool>’ option.

If reporting bugs, run virt-v2v with debugging enabled and include the 
complete output:

  virt-v2v -v -x [...]

**Comment by luca-af** [comment]
Hai utilizzato lo script all'ultima versione?

**Comment by Procsiab** [comment]
Comunque, sulla guida è scritto cosa fare nel caso di un errore con lo storage pool: https://github.com/extraordy/rh024/blob/master/guides/kvm-install/README.md#errore-sul-pool-di-archiviazione

**Comment by tuxerrante** [comment]
Partendo da un sistema Ubuntu like è necessario utilizzare una differente machine?
```
$ virsh create --validate rh024.xml
error: Failed to create domain from rh024.xml
error: internal error: process exited while connecting to monitor: 2020-04-09T13:11:30.964510Z qemu-system-x86_64: -machine pc-q35-4.1,accel=kvm,usb=off,vmport=off,dump-guest-core=off: unsupported machine type 'pc-q35-4.1'
```
Per ora ho risolto installando da zero la 8.1 in KVM tramite iso, dopo aver inserito i permessi in /etc/libvirt/qemu.conf
```
user = "root"
group = "root"

```
