### ISSUE TITLE
user e password della macchina?

### ISSUE THREAD

**Issue by brennomessana** [extraordy/rh024#29]

**Comment by zikkeddu** [comment]
user non amministrativo:

student/student

utente root:

root/redhat

**Comment by gianlucaceci** [comment]
se intenti quelle dalla vm che ci hanno fornito sono descritte; comunque sono root/redhat

**Comment by Procsiab** [comment]
Trovate nome utente e password sulla pagina principale delle guide: https://github.com/extraordy/rh024/tree/master/guides/vbox-install#credenziali-di-accesso-per-la-macchina-virtuale
