### ISSUE TITLE
Linux e cyber security

### ISSUE THREAD

**Issue by manuelcastellani** [extraordy/rh024#30]
Lavoro nella cyber security, quanto e perche`e` importante secondo voi in questo ambito?

**Comment by Procsiab** [comment]
Io le risponderei dicendole che, dato che praticamente tutte le infrastrutture di rete utilizzano dispositivi che montano un sistema operativo basato su Unix / Linux / BSD, comprendere i meccanismi di basso livello del sistema o del kernel è un modo per comprendere quali sono le vulnerabilità e quali possano essere verosimilmente sfruttate. Questa è la mia opinione, tenendo in conto che non sono un esperto del settore
