### ISSUE TITLE
copia ed incolla non funziona nella macchina virtuale in virtual box?

### ISSUE THREAD

**Issue by MarioDeFilippis** [extraordy/rh024#34]

**Comment by ValentinoUberti** [comment]
Dovrebbe installare le guest-additions:
https://www.virtualbox.org/manual/ch04.html

**Comment by Procsiab** [comment]
Buongiorno, potrebbe fornire maggiori informazioni sul contesto in cui si trova: Sistema Operativo e versione di VirtualBox per esempio

**Comment by MarioDeFilippis** [comment]
Windows 10x64 versione 1909 18363.720
VirtualBox 6.018
