### ISSUE TITLE
VM con Hyper-v Microsoft

### ISSUE THREAD

**Issue by maxc72** [extraordy/rh024#36]
Sto cercando di installare RH su un vm Hyper-v (ho scaricato l'iso dal sito red hat) ma dopo l'installazione la macchina non si avvia. Ci sono settaggi particolari per la vm?

**Comment by kowalski7cc** [comment]
Ciao, stai installando in modalità Generazione 1 o Generazione 2?

**Comment by maxc72** [comment]
ho provato tutte e due :)

**Comment by maxc72** [comment]
Quindi non c'è soluzione?

**Comment by kowalski7cc** [comment]
@maxc72 Devo verificare con una installazione per vedere se riesco a riprodurre il problema

**Comment by maxc72** [comment]
Grazie, è da ieri sera che provo diverse configurazioni, ma sempre con lo stesso risultato, ho anche cercato sul web, ci sono dei video, seguiti passo passo ma non va...

**Comment by maxc72** [comment]
Salve sono riuscito a far partire la macchina, ma ho dovuto scaricare la 8.1, la stessa macchina con la 8.0 non funzionava

**Comment by kowalski7cc** [comment]
Perfetto, grazie per aver condiviso la soluzione!

**Comment by c0redump-gh** [comment]
Salve maxc72,
io ho seguito questa procedura per utilizzare l'immagine della VM fornita da extraordy, non utilizzando la ISO quindi, ho pensato di riallacciarmi al suo messaggio perché magari qualcuno è interessato a utilizzare l'immagine così come è stata fornita da extraordy:

- ho convertito in formato vhdx i dischi vmdk dopo averli estratti dall'ova fornito da extraordy
- ho creato una VM Hyper-V (generazione 1) con 1 core, 2 GB di RAM e 2 schede di rete
- ho agganciato:
   1) il vhdx del primo disco al controller: "Controller IDE 0" – "Percorso: 0"
   2) il vhdx del secondo disco al controller: "Controller SCSI – Percorso: 0"
   3) il vhdx del terzo disco al controller: "Controller SCSI – Percorso: 1"
   4) il vhdx del quarto disco al controller: "Controller SCSI – Percorso: 2"
- ho avviato la macchina virtuale selezionando dal menu di grub l'entry relativa al rescue mode: "Red Hat Enterprise Linux (0-rescue ...)
- in questo modo la VM si avvia e non si blocca con la schermata nera.
- mi sono loggato sulla VM utilizzando l'utenza "root" password "redhat"
- ho rigenerato l'initrd con questo comando: "dracut -f /boot/initramfs-4.18.0-147.el8.x86_64.img 4.18.0-147.el8.x86_64"
- a questo punto riavviando la VM ho potuto farla partire in modalità normale (la prima entry nel menù di grub) senza riscontrare più la schermata nera.

Ho anche effettuato un export della VM correttamente convertita (funzionante) che può essere importata su Hyper-V ma prima di uploadarla da qualche parte vorrei aver rassicurazioni di non violare l'EULA del prodotto. Se qualcuno di extraordy mi può contattare posso fornire l'immagine in modo tale che possa essere caricata nel repository github ufficiale "rh024".

Spero di esserle stato utile.

Cordiali saluti,
Davide Diana
