### ISSUE TITLE
Link simbolici

### ISSUE THREAD

**Issue by CristinaDeTullio** [extraordy/rh024#37]
Perchè usare dei link simbolici al posto dei file "reali"?

**Comment by ValentinoUberti** [comment]
I link simbolici possono per esempio essere applicati anche a directory e i dati non vengono duplicati.
https://www.ostechnix.com/explaining-soft-link-and-hard-link-in-linux-with-examples/

**Comment by Procsiab** [comment]
L'esempio più immediato che mi viene in mente: permettere di salvare i dati di un programma in una posizione diversa da quella di default.
Nel caso si debba usare un programma che salva i propri file in una posizione specifica, ma non si voglia riempire quel punto del filesystem o si voglia usare una partizione o un disco diverso, è possibile creare un link che punta alla destinazione desiderata ma si trova nella posizione richiesta dal programma in questione

**Comment by zikkeddu** [comment]
Due motivi banali, poi ce ne sono quanti ne vuoi:

- dipendenze: 

per far funzionare il programma X mi serve la libreria Y versione 2.1, ma sul sistema ho solo la versione 2.0. Da ricerca scopro che il programma X lavora bene anche con la versione 2.0 della libreria. Creo in directory un link simbolico libreria Y2.1 che punta a libreria Y2.0

- programmi in cartelle non previste:

installo il solito programma X che cerca per funzionare il programma Y nella cartella pippo.
ma il programma Y è installato nella cartella ciccio e ciò va benissimio così perchè tutti gli altri programmi lo cercano là.
creo nella directory pippo un simlink che punta al programma Y vero nella cartella ciccio, così anche il nostro programma X fuori dal coro lo può trovare, come da sue specifiche.
