### ISSUE TITLE
Credenziali

### ISSUE THREAD

**Issue by coos60** [extraordy/rh024#4]
Salve,
non sono riuscito a trovare le credenziali di accesso RH024. Ho cancellato per errore la mail.
Dove posso trovarle?
GRazie

**Comment by ValentinoUberti** [comment]
Salve cosa intende per 'credenziali di accesso RH024'? Se intende la mail informativa, può scrivere qui la sua email e le saranno rispedite.

**Comment by coos60** [comment]
cosa devo usare per fare il login ? utente, password?

**Comment by coos60** [comment]
la mia mail: cosimo.depinto@tin.it

**Comment by coos60** [comment]
![VirtualBox_RH024_08_04_2020_13_59_45](https://user-images.githubusercontent.com/7997922/78782200-ea8c9a00-79a1-11ea-978c-566f4236959e.png)

**Comment by coos60** [comment]
> 
> 
> Salve cosa intende per 'credenziali di accesso RH024'? Se intende la mail informativa, può scrivere qui la sua email e le saranno rispedite.

cosimo.depinto@tin.it
![VirtualBox_RH024_08_04_2020_13_59_45](https://user-images.githubusercontent.com/7997922/78782690-ad74d780-79a2-11ea-8eee-c94da65ddc5d.png)

**Comment by ValentinoUberti** [comment]
sono:
student/student, root/redhat

Ora aggiorniamo la guida. Grazie per la segnalazione

**Comment by coos60** [comment]
> 
> 
> sono:
> student/student, root/redhat
> 
> Ora aggiorniamo la guida. Grazie per la segnalazione

Prego
