### ISSUE TITLE
TTY

### ISSUE THREAD

**Issue by Pajale** [extraordy/rh024#40]
Si può spiegare meglio cosa significa TTY?

**Comment by rhslack** [comment]
In sostanza, tty è l'abbreviazione di teletype, ma è più popolarmente noto come terminale che consente di interagire con il sistema passando i dati (immessi) al sistema e visualizzando l'output prodotto dal sistema

**Comment by Procsiab** [comment]
Consiglio la lettura di questo articolo per approfondimenti e spunti:
https://dev.to/napicella/linux-terminals-tty-pty-and-shell-192e
