### ISSUE TITLE
sottoscrizione Macchina virtuale

### ISSUE THREAD

**Issue by AnnaLa** [extraordy/rh024#42]
non riesco a sottoscrivere la macchina virtuale nonostante mi sia inscritta su redHat.

**Comment by Procsiab** [comment]
Buongiorno, ha provato a seguire la [**guida**](https://github.com/extraordy/rh024/tree/master/guides/rhdev-subscribe)?
Cosa di preciso non funziona o non riesce a fare?

**Comment by AnnaLa** [comment]
si seguita la guida, montata la virtual machine quando sottoscrivo la macchina con il comando:
subscription-manager register --username annalaura78 --password ******

ho come risposta 
401-Unauthorized

**Comment by Procsiab** [comment]
Per caso ha già provato ad eseguire i comandi seguenti, all'interno della macchina virtuale, come utente root:
```
subscription-manager remove --all
subscription-manager unregister
subscription-manager clean
```

**Comment by AnnaLa** [comment]
appena eseguiti riprovato a registrare la macchina ma ho la stessa risposta.

**Comment by Procsiab** [comment]
Potrebbe mostrare la risposta completa? O compare solo `401-Unauthorized`?

**Comment by AnnaLa** [comment]
![Cattura](https://user-images.githubusercontent.com/9199003/78902932-c18c0800-7a7a-11ea-8040-b4acee5cde3a.JPG)

**Comment by Procsiab** [comment]
Al momento mi viene in mente che:
- magari la sua password contiene caratteri come & ! oppure "
- magari ha usato un Red Hat ID differente da `annalaura78` in [questo](https://github.com/extraordy/rh024/blob/master/guides/rhdev-subscribe/img/subscribe-rhdev-01.PNG) punto della registrazione

In caso contrario, vedrò di cercare più a fondo: finora nessuno ha ancora manifestato un problema simile

**Comment by AnnaLa** [comment]
ho utilizzato un carattere speciale ma non quelli indicati.
se riprovo a registrarmi con il mio user ho:
![image](https://user-images.githubusercontent.com/9199003/78904346-a8845680-7a7c-11ea-994c-306fb9013659.png)

**Comment by ValentinoUberti** [comment]
La combinazione utente/password non è riconosciuta. Riesce a loggarsi da web con quelle credenziali? Che carattere speciale ha utilizzato nella password?

**Comment by AnnaLa** [comment]
Risolto:
mi sono loggata sul portale redhad e ho cambiato la password, nello specifico eliminando il carattere speciale.
ho riprovato a registrare con la nuova password ed ha funzionato.

Grazie.

**Comment by AnnaLa** [comment]
avevo usato il $

**Comment by ValentinoUberti** [comment]
Bene

**Comment by Procsiab** [comment]
Riguardo a questo problema: usando il comando `subscription-manager` senza alcun parametro a seguire, la password viene richiesta su una riga a parte e sono accettati tutti i caratteri che è possibile inserire da tastiera: se volesse usare la password precedentemente scelta, dovrebbe essere in grado di farlo in questo modo
