### ISSUE TITLE
install macchina virtuale

### ISSUE THREAD

**Issue by ghost** [extraordy/rh024#43]
![Capture](https://user-images.githubusercontent.com/63402005/78902015-79b8b100-7a79-11ea-9a3b-be4c480a9247.PNG)

This system is registered to red hat subscription management, but is not receiving updates

Error: there are no enabled repositories in /etc/yum.repos.d" 

Come risolvere?

**Comment by gianlucaceci** [comment]
ti dice che è già registrato quindi se è devi mettere il --force alla fine del comando subscription

**Comment by ghost** [comment]
ho provato ma non va

**Comment by gianlucaceci** [comment]
prova a deregistralla subscription-manager remove --all 
e poi registrala nuovamente e verifica che cmq la tua macchina riesce ad uscire su internet

**Comment by Procsiab** [comment]
Per rimuovere interamente tutti i dati delle sottoscrizioni da `subscription-manager`, consiglio di usare i comandi in fondo alla [**guida**](https://github.com/extraordy/rh024/blob/master/guides/rhdev-subscribe/README.md#errori-con-subscription-manager)

**Comment by ghost** [comment]
Ho seguito la guida, ho fatto la ri-sottoscrizione alla subscription, ho avviato lo script per installare la macchina virtuale ma ora mi dà questo problema: 
![Capture](https://user-images.githubusercontent.com/63402005/78906843-27c75980-7a80-11ea-9af1-4922c1612ff7.PNG)

**Comment by Procsiab** [comment]
Provi ad eseguire i comandi mostrati nella [procedura manuale](https://github.com/extraordy/rh024/tree/master/guides/kvm-install#2-installazione), a partide da:
```
sudo systemctl enable libvirtd
sudo systemctl start --now libvirtd
```

**Comment by ghost** [comment]
Ho incontrato anche il problema del pool storage e seguendo la guida ho proseguito. Ma ad un certo punto mi dice questo: 
![Capture](https://user-images.githubusercontent.com/63402005/78909393-bb4e5980-7a83-11ea-9570-dbb6cc6a5b66.PNG)

**Comment by gianlucaceci** [comment]
ma dice che non supporta sistemi x86_64; il tuo è per caso a 32B?

**Comment by ghost** [comment]
> ; il tuo è per caso a 32B?

Come posso verificarlo? 
Scusami, sono una principiante ancora

**Comment by gianlucaceci** [comment]
Basta che usi il comando uname -a

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/63402005/78913202-f2733980-7a88-11ea-8f6a-3e515c6a3d79.PNG)

**Comment by gianlucaceci** [comment]
è a 64bit allora devi solo vedere se a livello di bios hai tutto abilitato per la virtualizzazione

**Comment by ghost** [comment]
immagino di sì visto che avevo già un altra macchina virtuale...

**Comment by ValentinoUberti** [comment]
L'errore è 
```
could not find capabilities for arch=x86_64 domaintype=kvm
```
Questo indica che probabilmente il module kvm non è stato caricato correttamente.

Servirebbe l'output di:

```
lsmod | egrep 'kvm'
```
e

```
dmesg | grep kvm
```
