### ISSUE TITLE
UTENTE

### ISSUE THREAD

**Issue by Pajale** [extraordy/rh024#44]
QUANDO CREO UN UTENTE COME FACCIO AD AGGIUNGERLO AL GRUPPO ROOT? CIOSè DARGLI PRIVILEGi elevati?

**Comment by Procsiab** [comment]
Esiste un gruppo per gli utenti amministratori chiamato `wheel`: per aggiungere un utente `pippo` a questo gruppo, può usare il comando
```
usermod -aG wheel pippo
```
Questo comando va eseguito da un utente che abbia già privilegi di amministratore

**Comment by fawkes15** [comment]
aggiungere l'utente nel file sudoers è concettualmente sbagliato?

**Comment by extraordy** [comment]
no
