### ISSUE TITLE
password con salt e sha256

### ISSUE THREAD

**Issue by parided** [extraordy/rh024#45]
Come si fa a creare una password con salt e sha256 o superiore?

**Comment by luca-af** [comment]
Spiega meglio cosa vuoi fare:

- Vuoi creare una stringa con password già hashata e con un determinato sale?
- Vuoi che la password venga salvata con sale e hash sha256?
- Vuoi modificare i parametri di sale ed hash usati da passwd?

**Comment by parided** [comment]
Semplicemente quando si crea un utente, è possibile fargli creare una password che utilizzi salt e sha256?

**Comment by luca-af** [comment]
La password viene già salvata hashata nel file `/etc/shadow`. Se vuoi richiedere una complessità specifica della password o cambiare le impostazioni dell'hashing devi modificare i file contenuti in `/etc/pam.d/`

**Comment by parided** [comment]
Quindi, per capire meglio, devi aver installato già salt e sha256?

**Comment by luca-af** [comment]
TL;DR: 
No, non devi installare nulla.

Risposta più lunga:
C'è un fraintendimento.

sha256 non è un programma, è un algoritmo di hashing e le librerie che lo definiscono sono già installate di base, non confonderti con il programma che calcola l'hash sha256 dell'input che gli passi.

Il salt (o anche sale) è una stringa generica che viene usata per non avere un hash banale (pratica di sicurezza, non è fondamentale averlo, solo fortemente consigliato).

Il salt può essere anche generato automaticamente dai programmi che usano l'algoritmo sha256, ad esempio `passwd` genera un salt casuale e lo usa con l'algoritmo di hashing configurato (il default se non ricordo male è proprio sha256).

**Comment by parided** [comment]
Ah, ok. Ora è tutto più chiaro. Sinceramente non sapevo che generasse la password utilizzando salt e sha256. 
Io ero rimasto ad una password cifrata su base64
