### ISSUE TITLE
differenza tra yum update e yum upgrade

### ISSUE THREAD

**Issue by fawkes15** [extraordy/rh024#46]
In quali casi usare uno o l'altra opzione?

**Comment by myfoxx** [comment]
UPDATE

yum update nomepacchetto //verrà aggiornato un progrmma chiamato nomepacchetto

yum update nomepacchetto nomepacchetto2 // verranno aggiornati due programmi,chiamati rispettivamente nomepacchetto e nomepacchetto2
yum update //in questo modo verranno aggioranti tutti i pacchetti presenti nella machina.Il processo potrebbe richiedere un tempo abbastanza elevato
NOTA:lanciando yum update verrà aggiornato anche il kernel

UPGRADE:aggiornare anche pacchetti obsoleti
Il comando

yum upgrade nomepaccheto nomepacchetto2

svolge una funzione simile al comando "yum update nomepacchetto",la differenza è rappresentata dal fatto che yum upgrade aggiornerà anche pacchetti "obsoleti"(cioè non più aggiornabili) .
E' utile aggiornare il sistema tramite yum upgrade se si desidera cambiare versione della distribuzione aggiornando(per esempio) Fox1.0 a Fox 2.0
