### ISSUE TITLE
Differenza tra yum/dnf e snap?

### ISSUE THREAD

**Issue by Dantesk** [extraordy/rh024#47]
Qual'è la differenza ?

**Comment by Procsiab** [comment]
Dalla [**documentazione**](https://snapcraft.io/docs/getting-started) di Snap:
> uno snap è un bundle di un'applicazione con le sue dipendenze che funziona senza modifiche su differente piattaforme Linux

Invece dnf e yum sono gestori di paccehtti in formato RPM
