### ISSUE TITLE
Installazione driver mac e cambio lingua tastiera

### ISSUE THREAD

**Issue by JeyDi** [extraordy/rh024#49]
Ciao!
Sto eseguendo la VM da Virtualbox su Mac, ho alcuni problemi nell'utilizzo: come l'impossibilità di scrollare la finestra della shell.
Questo è dovuto alla mancanza dei driver necessari? Come faccio as installarli?

Inoltre come faccio per cambiare lo schema della tastiera? Non ho la tastiera italiana, ma quella internazionale.

Grazie mille!

**Comment by Procsiab** [comment]
Buongiorno, per quanto riguarda lo scorrimento della finestra della shell: se sta usando la macchina virtuale proposta nella nostra guida, essa è priva di ambiente desktop dunque non è possibile scorrere il terminale.
Per quanto riguarda lo schema della tastiera, basta dare uno sguardo alla [**guida**](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/s1-changing_the_keyboard_layout) ufficiale di Red Hat
