### ISSUE TITLE
VM creata - Problemi con Attivazione Sottoscrizione 

### ISSUE THREAD

**Issue by Pajale** [extraordy/rh024#5]
Buon giorno, ho effettuato la registrazione, scaricato il file OVA per VB ed avviato in modalità normale la VM per il webinar di domani. 
Appena provo a lanciare sulla shell il comando di registrazione con email e password immesse nel modulo di registrazione RH, mi viene risposto : HTTP error (401 - Unautorized): Service not avaible, please try again later

**Comment by Procsiab** [comment]
Buongiorno, è possibile che lei abbia eseguito il comando `subscription-manager register` usando come `username` la sua email di registrazione e non il nome utente? Per intenderci, mi riferisco alla stringa impostata come Red Hat ID in fase di registrazione: ![foto](https://github.com/extraordy/rh024/blob/master/guides/rhdev-subscribe/img/subscribe-rhdev-01.PNG)

**Comment by Pajale** [comment]
si ho inserito la mail , andava inserito il nome utente?

**Comment by Procsiab** [comment]
Stando alla documentazione di Red Hat, si:

> The system should be registered with Red Hat Login Id instead of email ID because RHSM's candlepin searches for login username/Id under /subscription/users/loginID directory.

EDIT: mi faccia sapere se usando l'ID la sua installazione è stata registrata correttamente

**Comment by Pajale** [comment]
ho seguito la guida che avete pubblicato qui su GitHub, indicate specificatamente di inserire la mail che è stata inserita in fase di registrazione. C'è modo di recuperare il nome utente?

**Comment by Pajale** [comment]
ok GRAZIE - FUNZIONA! era il nome utente e non la posta elettronica - Grazie 1000
