### ISSUE TITLE
Repository locale 

### ISSUE THREAD

**Issue by goandy84** [extraordy/rh024#50]
In un ambiente Enterprise, è possibile utilizzare un server con subscription per creare un mirror locale al quale far accedere per aggiornamenti e upgrade diversi client privi di subscription?

**Comment by gianlucaceci** [comment]
si configurando un server satellite o uno in cui condivide una local repo. il più consigliato è satellite o l'opensource spacewal

**Comment by goandy84** [comment]
Grazie per la risposta, quindi paradossalmente non è necessario acquistare una licenza per ogni Desktop in azienda ma basterebbe licenziare solo il server dedicato a creare il mirror?

**Comment by gianlucaceci** [comment]
paradossalmente si ma a livello poi di gestione OS si. quindi dipende a che livello di assistenza si vuole accedere

**Comment by luca-af** [comment]
No, non è esattamente la stessa cosa. 

Satellite fornisce si un modo per distribuire i pacchetti internamente, ma richiede delle licenze specifiche per quante macchine registrare.
Se serve per delle macchine desktop è possibile anche prendere delle licenze desktop che hanno un costo diverso da quelle server.

Pagare le licenze per una sola macchina e poi distribuire quei pacchetti ad altre fa perdere il supporto, inoltre viola i termini della licenza acquistata.
Se non si vuole pagare la licenza per quelle macchine tanto vale installare una centos/fedora, tanto non si avrebbe comunque il supporto da parte di Red Hat.
