### ISSUE TITLE
differenze tra centos e rhel per pacchetti

### ISSUE THREAD

**Issue by fra42** [extraordy/rh024#51]
Gaetano ha accennato a quella tra fedora e rhel ma per quella tra rhel e centos?

**Comment by luca-af** [comment]
Grossomodo i pacchetti sono identici. Solitamente il procedimento per rilascio di una nuova versione di centos inizia in seguito al rilascio di una nuova versione di rhel.

**Comment by ValentinoUberti** [comment]
The new CentOS Stream is a rolling-release distro that tracks just ahead of Red Hat Enterprise Linux (RHEL) development, positioned as a midstream between Fedora Linux and RHEL. For anyone interested in participating and collaborating in the RHEL ecosystem, CentOS Stream is your reliable platform for innovation

Centos compila i pacchetti utilizzando i sorgenti messi a disposizione da RedHat
Centos Stream riceve aggiornamenti più frequenti da Fedora
