### ISSUE TITLE
differenza con CoreOS

### ISSUE THREAD

**Issue by antoninoromeo** [extraordy/rh024#52]
Ciao, 
vorrei chiedervi che differenza ci sia con CoreOS.
Grazie mille.

**Comment by ValentinoUberti** [comment]
CoreOS è un SO immutabile ed è attualmente il SO utilizzato per esempio in Openshift.

http://coreos.com/

**Comment by antoninoromeo** [comment]
@ValentinoUberti  grazie mille ! ha presto il posto di Atomic?

**Comment by ValentinoUberti** [comment]
Esatto! per OCP 3.11 c'era Atomic...
