### ISSUE TITLE
File di configurazione di default /etc

### ISSUE THREAD

**Issue by xclaudiov** [extraordy/rh024#53]
Ciao a tutti, nel corso si è parlato che i file di configurazione del sistema su /etc/ sono quelli modificati.
Qual'è il path dei file di configurazione di default?

**Comment by AldrovandiA** [comment]
Interessa anche ame.

**Comment by Procsiab** [comment]
| cartella | scopo |
|-|-|
|/etc|file di configurazione specifici per il sistema|
|/usr|software installato e dati in sola lettura dei programmi|
|/var|dati variabili specifici per il sistema che sono persistenti (database, cache,log)|
|/run|dati di runtime per i processi in esecuzione dall'ultimo avvio|

Vi riferite a una di queste cartelle in particolare?

**Comment by xclaudiov** [comment]
Ciao Mi spiego meglio: sulla RHEL8 mi è sembrato di capire che i file di configurazione sotto /etc sono quelli "modificati"... ma che esiste un altro path dove sono presenti quelli di "default non modificati".

Qual'è il path di quelli di default?

**Comment by ValentinoUberti** [comment]
Per esempio i file di unit di systemd:

/usr/lib/systemd/system
/etc/systemd/system

La prima è quella di default di sistema. Se lo stesso file esiste anche la seconda directory in /etc viene utilizzato quest'ultimo

**Comment by xclaudiov** [comment]
Ok grazie... questo vale ad esempio anche sul file /etc/ssh/sshd_config?

**Comment by ValentinoUberti** [comment]
no
