### ISSUE TITLE
network 'default' is not active

### ISSUE THREAD

**Issue by mauriziomarini** [extraordy/rh024#59]
Sono in Fedora31 e non risco ad avviare il 'domain' RH024
cmq ho una mia RH 8.1 ma era giusto per capire

sudo virsh start RH024
errore: Impossibile avviare il dominio RH024
errore: Requested operation is not valid: network 'default' is not active

Grazie

**Comment by Procsiab** [comment]
Apparentemente la rete chiamata default non è attiva: potrebbe incollare qui l'output del comando
```
sudo virsh net-list --all
```
Se fosse diverso dal seguente, allora la rete "default" non è attiva o nemmeno presente:
```
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
```

**Comment by mauriziomarini** [comment]
sudo virsh net-list --all
 Nome              Stato        Avvio automatico   Persistent
---------------------------------------------------------------
 default           non attivo   yes                yes
 docker-machines   attivo       yes                yes

avevo installato mini-shift
temo che faccia confusione
come si attiva il default e si disattiva docker-machines?

**Comment by sstagnaro** [comment]
Creala a mano con:

```
mkdir -p /var/lib/libvirt/images

virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images

virsh pool-start default

virsh pool-autostart default
```

**Comment by mauriziomarini** [comment]
Grazie, alla fine e' partito, c'e' anche la tun1 di openvpn che dava fastidio
A presto
