### ISSUE TITLE
wget su drive.google.com non funziona

### ISSUE THREAD

**Issue by lota** [extraordy/rh024#6]
wget "https://drive.google.com/open?id=19id0zA-XKeTF_3_jm0taFeFhxNmcDo_N" -O rh024.tar.gz
non funziona sul mio sistema

col browser funziona e fa scaricare

**Comment by emanueleg** [comment]
E' un problema noto (in particolare con i file più grandi di 100MB). Si può aggirare con un piccolo _hack_...

`wget --quiet --save-cookies /tmp/rh024-cookie --keep-session-cookies "https://drive.google.com/uc?export=download&id=19id0zA-XKeTF_3_jm0taFeFhxNmcDo_N" -O /dev/null`

`wget --keep-session-cookies --load-cookies /tmp/rh024-cookie "https://drive.google.com/uc?export=download&confirm=$(awk '/_warning_/ {print $NF}' /tmp/rh024-cookie)&id=19id0zA-XKeTF_3_jm0taFeFhxNmcDo_N" -O rh024.tar.gz`

**Comment by extraordy** [comment]
A breve verrà inserito uno script per il download
