### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by gpn1971** [extraordy/rh024#60]
è possibile configurare un cluster linux, magari con un'interaccia grafica ?

**Comment by ValentinoUberti** [comment]
Di che cluster stai parlando?

**Comment by gpn1971** [comment]
di macchina e anche di db

**Comment by gpn1971** [comment]
2 o più macchina clusterizzate, tipo hacmp di aix

**Comment by ValentinoUberti** [comment]
La sola installazione di RHEL8 non permette l'installazione di cluster da interfaccia grafica.
