### ISSUE TITLE
SSH con Mac e VirtualBox

### ISSUE THREAD

**Issue by Stonerpr91** [extraordy/rh024#61]
Salve, come fare per collegarmi tramite SSH dal mio Mac alla macchina virtuale su Virtualbox?

**Comment by Procsiab** [comment]
Non abbiamo previsto un accesso SSH alla maccchina: non mostreremo questa procedura durante il corso, tuttavia dovrebbe essere facile configurare il suo sistema host e la macchina virtuale da una guida come [**questa**](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/s1-ssh-configuration)
