### ISSUE TITLE
RHEL 7 vs 8

### ISSUE THREAD

**Issue by bersanig** [extraordy/rh024#63]
quali sono le differenze e quindi le novità della 8?

**Comment by luca-af** [comment]
Le novità sono state brevemente viste durante l'rh024.
Ti lascio [qui](https://www.redhat.com/cms/managed-files/li-whats-new-rhel-8-infographic-f17210bf-201905-en.pdf) un documento riassuntivo di Red Hat  con le novità.

**Comment by sstagnaro** [comment]
Le differenze tra RHEL7 e RHEL8 sono il tema principale del corso [RH354](https://www.extraordy.com/corsi_red_hat/rh354/), durante il quale vengono illustrate le nuove tecnologie (VDO, Stratis, Yum4, Podman, nftables, solo per citarne alcune) con specifici capitoli di approfondimento e laboratori tematici.

Sullo stesso argomento segnalo però i seguenti documenti:
- [What's new in Red Hat Enterprise Linux 8?](https://www.redhat.com/en/resources/whats-new-rhel-8-infographic) → infografica con il riassunto delle principali novità (divulgativo, non tecnico);
- [Considerations in adopting RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/index) → documento tecnico che copre nel dettaglio le differenze con le versioni precedenti di RHEL.
