### ISSUE TITLE
ulteriori info su questi argomenti (selinux, container ecc)

### ISSUE THREAD

**Issue by fra42** [extraordy/rh024#64]
risorse free per rivedere e approfondire questi argomenti?

**Comment by Procsiab** [comment]
Con una sottoscrizione Red Hat Developer (che è gratuita) è possibile accedere alla [**documentazione**](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/) di Red Hat al riguardo; soprattutto SELinux e i Linux Container sono componenti del kernel, e quello che trovi tra quel materiale è valido anche sulle altre distribuzioni GNU/Linux
