### ISSUE TITLE
cockpit, grafana e altre interfacce

### ISSUE THREAD

**Issue by fra42** [extraordy/rh024#68]
Ciao, cockpit sembra interessante, conosco anche grafana.... cosa mi sapete dire di queste tecnologie, le differenze ecc?

cockpit può includere grafana?

**Comment by Pr1meSuspec7** [comment]
posso avere un unico cockpit che monitora più macchine rh?

**Comment by Procsiab** [comment]
@Pr1meSuspec7 potrebbe spostare la sua domanda in un'altra issue, dato che non è correlata con questa qui?

**Comment by Procsiab** [comment]
@fra42 cockpit è un progetto open source: https://github.com/cockpit-project/cockpit
Se lo desidera, può apportarvi le modifiche di cui ha bisogno; di base il progetto cockpit non usa il codice di Grafana.
