### ISSUE TITLE
Cockpit stabile su RH7 ?

### ISSUE THREAD

**Issue by mezzagianni** [extraordy/rh024#69]
Cockpit nella versione stabile verrà backportato su RH7 ?

**Comment by Procsiab** [comment]
Buongiorno, su RHEL 7 è possibile usare Cockpit; questa è la procedura di installazione descritta dalla [**guida ufficiale**](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/getting_started_with_cockpit/installing_and_enabling_cockpit)
