### ISSUE TITLE
Problema iscrizione Red Hat Developer

### ISSUE THREAD

**Issue by elenagal83** [extraordy/rh024#7]
Buongiorno,
al momento della registrazione viene richiesto la professione. Io sono un tecnico di laboratorio che fa ricerca, ma la mia professione non è nell'elenco. Cosa devo segnare? Grazie

**Comment by ValentinoUberti** [comment]
Salve, ai fini dell'iscrizione per questo corso il ruolo non è determinante, scelga pure quello che si avvicina di più al suo.
