### ISSUE TITLE
Doc delta RHEL7-8

### ISSUE THREAD

**Issue by vvinci00** [extraordy/rh024#77]
Il doc mostrato precedentemente in merito al delta RHEL 7-8 verrà condivisa?

**Comment by sstagnaro** [comment]
Il documento mostrato in realtà è la Student Guide dello [RH354](https://www.extraordy.com/corsi_red_hat/rh354/), ovvero il corso dedicato a coprire le differenze tra RHEL7  e RHEL8. Per questa ragione non può essere divulgato.

Sullo stesso argomento segnalo però i seguenti documenti:
- [What's new in Red Hat Enterprise Linux 8?](https://www.redhat.com/en/resources/whats-new-rhel-8-infographic) → infografica con il riassunto delle principali novità (divulgativo, non tecnico);
- [Considerations in adopting RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/index) → documento tecnico che copre nel dettaglio le differenze con le versioni precedenti di RHEL.
