### ISSUE TITLE
nmcli connection su quale device

### ISSUE THREAD

**Issue by aleSBT** [extraordy/rh024#79]
per far funzionare cockpit devo creare la connection con nmcli? se si, devo usare l'unica interfaccia del mio pc per attivarla o posso creare una nuova interfaccia?

**Comment by Procsiab** [comment]
Buongiorno, se intende utilizzare Cockpit tra la macchina virtuale e il sistema host, dopo aver [**installato e attivato**](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/getting_started_with_cockpit/installing_and_enabling_cockpit) il servizio, deve gestire l'inoltro della porta 9090 dal guest a una porta sull'host e poi connettersi col browser.
Se usa un sistema operativo GNU/Linux, le basta installare il paccehtto cockpit e poi lanciare il comando `/usr/libexec/cockpit-desktop /` per avviare una istanza di Cockpit relativa alla sua macchina
