### ISSUE TITLE
Problemi DNS se collegati con VPN ( a rete aziendale nel mio caso )

### ISSUE THREAD

**Issue by Kralizec99** [extraordy/rh024#8]
Volevo segnarli che durante al fase di registrazione , come riportato dalle vostre istruzione, ho avuto un problema a raggiungere l'host a causa del DNS che non funxionava ( nella VM RH024 )
Questo sembra riconducibile al fatto che nirmalmente il mio PC e' collegato alla rete aziendale tramite VPN ( CIssco Anyconnect )

Ho risolto chiudendo la vm , lanciando il seguente comando 

`VBoxManage modifyvm RH024 --natdnshostresolver1 on`

e ripartendo .

Spero che possa essere di aiuto anche ad altri

**Comment by ValentinoUberti** [comment]
Grazie della segnalazione e della soluzione.
