### ISSUE TITLE
Installazione di Openshift - come mai docker e non podman??

### ISSUE THREAD

**Issue by Dantesk** [extraordy/rh024#80]
Come mai durante l'installazione attuale di Openshift viene utilizzato docker e non podman?

**Comment by Dantesk** [comment]
Ci sono delle differenze sostanziali per consigliare podman?

**Comment by kowalski7cc** [comment]
Ciao, Podman ha molte differenze sotto il cofano rispetto a Docker, come la possibilità di girare senza privilegi di root, il supporto a cgroups v2, l'assenza di un demone costantemente attivo, ecc...
Per un ulteriore approfondimento ti lascio il link di del talk di Dan Walsh: https://www.youtube.com/watch?v=YkBk52MGV0Y
