### ISSUE TITLE
differenza tra FEDORA e CENTOS

### ISSUE THREAD

**Issue by marpal71** [extraordy/rh024#81]

**Comment by kowalski7cc** [comment]
Ciao, la differenza è che CentOS segue il modello di rilasci e aggiornamenti di RHEL (https://access.redhat.com/support/policy/updates/errata) garantendo quindi circa 10 anni di vita per ogni release con una major ogni 5 anni.
Fedora invece ha un ciclo di aggiornamenti molto più rapido con una major ogni 6 mesi (In modo analogo a Ubuntu e Windows 10), garantendo però solo circa un anno di vita per release.
Fedora funziona come progetto di upstream per i RHEL, e di conseguenza CentOS, ossia fornisce la base dalla quale vengono derivate poi le major release delle distribuzioni enterprise.
