### ISSUE TITLE
aggiunta repository

### ISSUE THREAD

**Issue by aleSBT** [extraordy/rh024#82]
come aggiungo le repository per far funzinare yum?

**Comment by Procsiab** [comment]
Buongiorno, se intende aggiungere le repository ufficiali di Red Hat, segua la procedura mostrata sulla nostra [**guida**](https://github.com/extraordy/rh024/tree/master/guides/rhdev-subscribe) per la registrazione di una sottoscrizione e l'associazione del sistema.
