### ISSUE TITLE
credenziali per la vm 8

### ISSUE THREAD

**Issue by aeroli** [extraordy/rh024#83]
le credenziali per accedere alla Vm da laboratorio?

**Comment by Procsiab** [comment]
Buonasera, se si riferisce alla macchina virtuale proposta da noi, le credenziali sono nella [**guida**](https://github.com/extraordy/rh024/blob/master/guides/kvm-install/README.md#credenziali-di-accesso-per-la-macchina-virtuale) all'installazione
