### ISSUE TITLE
Buon pomeriggio, ho installato la Vm su win 7, ma vorrei installarla su ubuntu 18.04,è possibile'

### ISSUE THREAD

**Issue by lambert-art** [extraordy/rh024#84]

**Comment by myfoxx** [comment]
Installa virtualbox, segui gli stessi passaggi fatti per la macchina WIN.

**Comment by lambert-art** [comment]
Grazie

Il giorno gio 9 apr 2020 alle ore 18:06 Myfox <notifications@github.com> ha
scritto:
