### ISSUE TITLE
Cockpit - moduli

### ISSUE THREAD

**Issue by AlexDojoco** [extraordy/rh024#89]
Vorrei sapere se per cockpit sono disponibili moduli per tutti i servizi ospitabili su RHEL, tipo DNS, apache, ntp, stratis, ceph, etc

**Comment by ValentinoUberti** [comment]
I servizi che hai elencato sono sotto services.
Se intendevi plugin si. Per esempio installando il plugin per la gestione delle vm, le gestiremo da cockpit.
https://cockpit-project.org/guide/209/feature-virtualmachines.html

Altro esempio:
https://cockpit-project.org/guide/latest/feature-machines.html
