### ISSUE TITLE
HTTP error (401 -unauthorized) : service not available 

### ISSUE THREAD

**Issue by mrwys** [extraordy/rh024#9]
Ciao ho questo piccolo issue che non mi permette di completare il passo 4 presente nella vostra guida di iscrizione gratuita [qui](https://github.com/extraordy/rh024/blob/master/guides/rhdev-subscribe/README.md) restituendomi appunto l'errore sopra citato nel titolo , come potrei risolvere ?

**Comment by ValentinoUberti** [comment]
La login e password sono corretti? Con che email ti sei registrato a RedHat Developer?

**Comment by mrwys** [comment]
sono riuscito a risolvere chiedo scusa per il disagio causato da questo issue

**Comment by ValentinoUberti** [comment]
Nessun disagio, ci vediamo domani
