### ISSUE TITLE
c'è un modo di tradurre le configurazioni iptables in firewalld?  Come per la traduzione dai vecchi servizi /init.d a systemd

### ISSUE THREAD

**Issue by salvo92** [extraordy/rh024#90]

**Comment by ValentinoUberti** [comment]
Ciao un tool di conversione in automatico non mi risulta (bisognerebbe fare una ricerca)
firewall-cmd oltre alle rich-rules supporta anche le direct-rules

https://firewalld.org/documentation/man-pages/firewalld.direct.html
