### ISSUE TITLE
Politiche aggiornamento pacchetti

### ISSUE THREAD

**Issue by marianomacchi** [extraordy/rh024#95]
Quale sarebbe l'approccio consigliabile nella gestione dell'aggiornamento dei pacchetti?

Potrebbe essere automatizzato o sarebbe preferibile fosse sempre manuale?

**Comment by luca-af** [comment]
L'aggiornamento dei pacchetti è facilmente automatizzabile con dei playbook di Ansible ed è consigliato da fare.

Ovviamente, a seconda dei casi, puoi anche parametrizzare gli aggiornamenti con il palybook, in modo da separare quelli più generali da quelli che impattano applicazioni più sensibili (e.g. un webservice) per cui sono richieste attività particolari (non durante le ore di attività).
