### ISSUE TITLE
VM non raggiungibile da host fisico

### ISSUE THREAD

**Issue by goandy84** [extraordy/rh024#97]
Ciao, la macchina virtuale con scheda nat non è raggiungibile dall'host fisico che la ospita. al contrario riesco a pingare dalla VM il mio client e altre macchine nella rete.
Pensavo al firewall ma ho buttato giu il servizio e ancora non riesco a raggiungere la VM.

**Comment by giomono** [comment]
Anche io lo stesso problema,
installato in VirtualBox la macchina virtuale del corso.
Effettuato la registrazione e dopo aver installato i pacchetti httpd e colckpit, volevo accedere sia web ma la macchina fisica non ci accede.

Non ho fatto alcuna configurazione sulla rete della macchina virtuale...
Infatti ha come indirizzo Ip un indirizzo tipo 10.0...

Bisogna effettuare una configurazione particolare per far vedere la virtuale da quella fisica?

Grazie

**Comment by Kakihara73** [comment]
oltre ad installare i pacchetti vanno anche avviati con
systemctl start httpd.service 
systemctl start cockpit.service

inoltre configurare l'indirizzo ip manualmente come indicato nel corso, magari è semplicemente questo il problema di raggiungibilità della VM

EDIT: inoltre cockpit agisce di default sulla porta 9090 quindi nel browser oltre all'indirizzo ip va indicata anche la porta

**Comment by giomono** [comment]
Queste le mie configurazioni:

Macchina Fisica Win10 con MobaXTerm
	ifconfig
		VirtualBox Host-Only Ethernet Adapter
			inet addr:192.168.56.1
		Intel(R) Dual Band Wireless-AC 3165
			inet addr:192.168.178.26

VirtualBox
	ip a s
		2: enp0s3 inet 192.168.178.29/24  --> Quindi nella stessa rete della mia macchina fisica
	
	ss -tylpn | grep -E "80|9090"
		tcp LISTEN 0 128 *:80 .....
		tcp LISTEN 0 128 *:9090 .....
	
	firewall-cmd --list-services
		cockpit dhcpv6-client http ssh
	
	curl -ks 192.168.178.29:80
		Ottengo il contenuto HTML correttamente
![image](https://user-images.githubusercontent.com/35068670/78972003-0bbdc980-7b0d-11ea-9b93-476efdc7859a.png)

	curl -ks 192.168.178.29:9090
		Ottenog il contenuto Html correttamente...

A questo punto ritorno nella mia macchina Fisica, su MobaXTerm
	ping 192.168.178.29
		Pacchetti Trasmessi = 4, Ricevuti = 4
	
	telnet 192.168.178.29
	telnet 192.168.178.29 9090
		Entrambi funzionano correttamente
	
	curl -ks 192.168.178.29:80
	curl -ks 192.168.178.29:9090
	Accesso da Browser http://192.168.178.29/
	Accesso da Browser http://192.168.178.29:9090/
		Questi 4 ultimi comandi non Funzionano,
                 il Curl mi da un risultato vuoto,
                da Browser ricevo il messaggio di "Impossibile raggiungere il sito"


Il problema sembra che la macchina virtuale non'è accessibile dall'esterno, quindi non saprei cos'altro aggiungere poichè la cosa strana è che col ping/telnet ci arrivo ma con curl o browser non va

**Comment by ValentinoUberti** [comment]
L'interfaccia di rete come è configurata?
Puoi provare a metterla in bridge?

**Comment by giomono** [comment]
Questa la config d Rete di Virtual Box
![image](https://user-images.githubusercontent.com/35068670/78978435-0a46ce00-7b1a-11ea-870b-d452dada0b1b.png)

Aggiungo che ho effettuato la stessa configurazione sul mio PC Fisso con XUbuntu 18.04 + VirtualBox 6.0 con la stessa configurazione di VirtualBox qui da Xubuntu da Browser riesco ad accedere correttamente alla macchina virtuale....

Quindi direi che è Win che non va.....

**Comment by ValentinoUberti** [comment]
Concordo.
