### ISSUE TITLE
docker / podman e containers

### ISSUE THREAD

**Issue by MauroLavezzari** [extraordy/rh024#99]
se faccio un ps su un worker node di un cluster K8s, vedo nell lista anche un processo per docker / podman e tanti processi quanti sono i container ospitati (oltre ovviamente agli altri processi attivi sul server)?

**Comment by ValentinoUberti** [comment]
Ciao Mario,
parlando di Openshift 4.x il servizio docker non viene utilizzato.
Puoi utilizzare l'utility crictl è la cli per CRI-compatible container runtimes.

se la runtime utilizzata è runc, puoi vedere i processi con runc list.
